tlpipe.kiyopy.custom_exceptions.DataError
=========================================

.. currentmodule:: tlpipe.kiyopy.custom_exceptions

.. autoexception:: DataError